### ISSUE TITLE
Respect to you 

### ISSUE THREAD

**Issue by kingsznhone** [SadPencil/Ra2CsfFile#1]
How do you find this magic operation?

`value = value.Select(v => (Byte)(~v)).ToArray(); // perform bitwise NOT to the bytes`

It's impressive.

**Comment by SadPencil** [comment]
In [https://modenc.renegadeprojects.com/CSF_File_Format](https://modenc.renegadeprojects.com/CSF_File_Format):

> Decoding the value
>
> To decode the value to a Unicode string, not every byte of the value data (or subtract it from 0xFF).
